spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://118.31.19.39:3306/sell?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    hikari:
      minimum-idle: 1
      connection-timeout: 36000000
      max-lifetime: 36000000



  #配置 springdataJPA
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null  # 全局 jsonInclude.Include.NOT_NULL
  redis:
    host: localhost
    port: 6379




#  mvc:
#    view:
#      prefix: "/"
#      suffix: ".html"




server:
  port: 8885
  servlet:
    context-path: /sell



wechat:
    mpAppid: wx59a58f94139b9dec
    mpAppSecret: 303a604d54da79c22fbb1e976d58990d
    mchId: 1579677461
    mchKey: meiyukai520shenye131411111111111
    keyPath: /Users/meiyukai/Documents/wechat_cert/1579677461_20200315_cert/apiclient_cert.p12
    notifyUrl: http://xiaomei.natapp1.cc/sell/pay/notify
    templateId:
      orderDeliver: YF6RV-nZHfSYZcFtu5LJ45YGDfjvCpMq7dmy6gIb3Fc
      newOrder: ZkWoJZftcl0pa6pj5X2JW78L6fDAr_0nJtcuKdNNdbU
      paid: -8QG_kNkMaHQjPVWrwfnEONNk5JhhBQ2pssmeAaHvOg
      avaOpenid: oRKFQs6eBbHAJlvc-IJwUGhMG22c
      buyerCancel: xnA45llXUXgMrmHUw2M_smiviXroDqFIQSz4OPRGCpY
      sellerCancel: t975WHy2HM7Yj9dtUpB7XHFd7dksZSAnWnAM5I-RTZo

sf:
  appid: 193251
  sign: d4b4da5480b54c2c8a70c4b5bb37342b



#logging:
#  pattern:
#    console: "%d - %msg%n"
#    file: /Users/meiyukai/Downloads/sell.log
##  path: /Users/meiyukai/Downloads/


mybatis:
  type-aliases-package:  com.meiyukai.domain
  type-handlers-package:  com.meiyukai.dao

url:
  wechatMpAuthorize: http://xiaomei.natapp1.cc/sell/wechat/userInfo
  sell: http://xiaomei.natapp1.cc/sell/


